#!/bin/bash

a=abc
b=abc

c=true
d=false

e=123
f=123

if [ $a == $b ];then
    echo "string == string test ok"
fi

if [ $a = $b ];then
    echo "string = string test ok"
fi

if [[ $a = $b ]];then
    echo "string = string test ok"
fi

#wrong int expression
#if [ $a -eq $b ];then
#    echo "a==b"
#fi

if [[ $a = $b || $a = "abc" ]];then
    echo "string || test ok"
fi

#wrong
#if [[ $a = $b -eq $a = "abc" ]];then
#    echo "string -eq test ok"
#fi



if [ $c = true ];then
    echo "true"
fi

if [ $c == true ];then
    echo "true"
fi

#wrong int expression
#if [ $c -eq true ];then
#    echo "true"
#fi



if [ $e = $f ];then
    echo "e==f"
fi

if [ $e == $f ];then
    echo "e==f"
fi

if [[ $e == $f ]];then
    echo "e==f"
fi

if [ $e -eq $f ];then
    echo "e==f"
fi

if [ $e = 123 -o $e = $f ];then
    echo ""
fi

if [ $e -eq 123 -o $f -eq 123 ];then
    echo ""
fi


if [[ $c = true || $c = false ]];then
    echo "bool"
fi

if [ $c = true ] || [ $c = false ];then
    echo "bool"
fi

if [ $c = true -o $c = false ];then
    echo "bool"
fi
